site_name: State of Midway
site_url: https://state-of-midway.github.io/documentation/
site_author: Longitude
site_description: N/A

theme:
  name: material
  features:
    - tabs

  logo: assets/logo.png
  favicon: assets/favicon.ico

  icon:
    repo: fontawesome/brands/github

  include_search_page: false
  search_index_only: true

  language: en

plugins:
  - search:
      separator: '[\s\-]+'
  - awesome-pages
  - git-revision-date-localized:
      type: date

markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Guidelines:
      - Game Rules: guidelines/game-rules.md
  - State Laws: laws.html
